/*
 * generated by Xtext 2.10.0
 */
package de.jro.tools.tests

import com.google.inject.Inject
import de.jro.tools.bob.Domainmodel
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(BobyInjectorProvider)
class BobyParsingTest{

	@Inject
	ParseHelper<Domainmodel> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
