/*
 * generated by Xtext 2.10.0
 */
package de.jro.tools


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class BobyStandaloneSetup extends BobyStandaloneSetupGenerated {

	def static void doSetup() {
		new BobyStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
